version: '3'
services:
  app:
    build: .
    working_dir: /stable-diffusion/src
    tty: true
    volumes:
      - ./outputs:/stable-diffusion/outputs
      - ./src:/stable-diffusion/src
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: always
